# SPDX-FileCopyrightText: 2021 Arthur Breitman

# SPDX-License-Identifier: LicenseRef-MIT-Arthur-Breitman

- message:
  - name: Redundant build-depends entry
  - depends:
    - base-noprelude
    - morley-prelude

- message:
  - name: Weeds exported
  - module:
    - name: Tree
    - identifier:
      - ingredients
      - main
  - module:
    - name: Test.Position
  - module:
    - name: Test.XToY
  - module:
    - name: Test.YToX
