# SPDX-FileCopyrightText: 2021 Arthur Breitman
# SPDX-License-Identifier: LicenseRef-MIT-Arthur-Breitman

resolver: lts-17.3

packages:
  - haskell

# You might have to update hackage index used by CI when you update
# packages in this list, see the comment at the top of the file
extra-deps:
  - git:
      https://gitlab.com/morley-framework/indigo.git
    commit:
      f564a0ea3ec66edb3fd074c75a1e9bc5a80f3d35 # master
    subdirs:
      - .
  - morley-prelude-0.4.2
  - morley-1.15.1
  - lorentz-0.12.0
  - hex-text-0.1.0.0
  - named-0.3.0.1
  - show-type-0.1.1
  - summoner-2.0.1.1
  - fmt-0.6.3.0
  - formatting-7.1.3

  - git: https://github.com/serokell/base-noprelude.git
    commit: 87df0899801dcdffd08ef7c3efd3c63e67e623c2
  - git: https://github.com/serokell/galois-field.git
    commit: 576ba98ec947370835a1f308895037c7aa7f8b71
  - git: https://github.com/serokell/elliptic-curve.git
    commit: b8a3d0cf8f7bacfed77dc3b697f5d08bd33396a8
  - git: https://github.com/serokell/pairing.git
    commit: cf86cf1f6b03f478a439703b050c520a9d455353
  - git:
      https://gitlab.com/morley-framework/morley.git
    # ^ CI cannot use ssh, so we use http clone here
    commit:
      a726d42f89f83aa794f381b5332a542b634ba057 # master
    subdirs:
      - code/cleveland
      - code/morley-client
  - git: https://github.com/int-index/caps.git
    commit: c5d61837eb358989b581ed82b1e79158c4823b1b
  - git: https://gitlab.com/morley-framework/morley-ledgers.git
    commit: 129df0364df17127941efe1beed052bf5c320d3b # master
    subdirs:
      - code/morley-ledgers
  - git: https://gitlab.com/morley-framework/morley-metadata.git
    commit: cf434b81bd54939855541abc320552adcefd1715 # master
    subdirs:
      - code/morley-metadata
  - tasty-1.4
  - tasty-ant-xml-1.1.8
  # Needed by `summoner-2.0.1.1`, not sure why it is not required in `indigo` or `baseDAO`.
  - generic-data-0.8.3.0
  - neat-interpolation-0.3.2.6
  - megaparsec-8.0.0
