# SPDX-FileCopyrightText: 2021 Arthur Breitman
# SPDX-License-Identifier: LicenseRef-MIT-Arthur-Breitman

.scheduled: &scheduled build.source == "schedule"
.not-scheduled: &not-scheduled build.source != "schedule"

.network-tests: &network-tests
  commands:
    - nix-build ci.nix -A packages.segmented-cfmm.tests.segmented-cfmm-test
    - nix run -f ci.nix tezos-client -c ./result/bin/segmented-cfmm-test
          --nettest-mode=only-network
          --nettest-data-dir "$(mktemp -d --tmpdir="$PWD")"
  retry:
    automatic:
      limit: 1
  timeout_in_minutes: 360

steps:
  - label: hlint
    if: *not-scheduled
    commands:
    - nix run -f ci.nix pkgs.hlint -c
        ./scripts/lint.sh

  - label: reuse lint
    if: *not-scheduled
    commands:
    - nix run -f ci.nix pkgs.reuse -c
        reuse lint

  - label: check trailing whitespace
    if: *not-scheduled
    commands:
    - .buildkite/check-trailing-whitespace.sh

  - label: xrefcheck
    if: *not-scheduled
    commands:
    - nix run -f ci.nix xrefcheck -c xrefcheck
    retry:
      automatic:
        limit: 1

  - label: check cabal files
    if: *not-scheduled
    commands:
    - nix run -f ci.nix stack2cabal pkgs.diffutils -c ./scripts/ci/validate-cabal-files.sh

  - label: build-ligo
    key: build-ligo
    if: *not-scheduled
    commands:
      - nix-build ci.nix -A build-ligo -o ./ligo-out/
    artifact_paths:
      - ligo-out/*

  - label: build-haskell
    key: build-haskell
    if: *not-scheduled
    commands:
    - nix-build ci.nix -A all-components

  - label: ligo-test
    if: *not-scheduled
    commands:
      - nix-build ci.nix -A packages.segmented-cfmm.tests.segmented-cfmm-test
      - ./result/bin/segmented-cfmm-test --nettest-mode=disable-network

  - label: ligo-test-local-chain-010
    if: *not-scheduled
    <<: *network-tests
    env:
      # this key is defined in local-chain bootstrap accounts list in
      # https://github.com/serokell/aquarius-infra/blob/master/servers/albali/chain.nix
      TASTY_NETTEST_IMPORT_SECRET_KEY: "unencrypted:edsk42cYfuawC5i3PmuS3Lq73pAzgrJyVNcv9CXQspM2dG4M9QMpeS"
      TASTY_NETTEST_NODE_ENDPOINT: "http://localhost:8733"

  - label: ligo-test-local-chain-011
    if: *not-scheduled
    <<: *network-tests
    env:
      # this key is defined in local-chain bootstrap accounts list in
      # https://github.com/serokell/aquarius-infra/blob/master/servers/albali/chain.nix
      TASTY_NETTEST_IMPORT_SECRET_KEY: "unencrypted:edsk42cYfuawC5i3PmuS3Lq73pAzgrJyVNcv9CXQspM2dG4M9QMpeS"
      TASTY_NETTEST_NODE_ENDPOINT: "http://localhost:8734"

  - label: ligo-test-granadanet-scheduled
    if: *scheduled
    <<: *network-tests
    env:
      # Note that testnet moneybag can run out of tz. If this happened, someone should transfer it some
      # more tz, its address: tz1Nbp1gNPMzn9MB9ZhBnfsajsaQBLYScdd5
      TASTY_NETTEST_IMPORT_SECRET_KEY: "unencrypted:edsk48WyaFHvsqLYQBrCBiRUdnPa7VduZbePo5UAbyMJRN8Eob5PvL"
      TASTY_NETTEST_NODE_ENDPOINT: "https://granada.testnet.tezos.serokell.team"

  - label: ligo-test-hangzhounet-scheduled
    if: *scheduled
    <<: *network-tests
    env:
      # Note that testnet moneybag can run out of tz. If this happened, someone should transfer it some
      # more tz, its address: tz1Nbp1gNPMzn9MB9ZhBnfsajsaQBLYScdd5
      TASTY_NETTEST_IMPORT_SECRET_KEY: "unencrypted:edsk48WyaFHvsqLYQBrCBiRUdnPa7VduZbePo5UAbyMJRN8Eob5PvL"
      TASTY_NETTEST_NODE_ENDPOINT: "https://hangzhou.testnet.tezos.serokell.team"

  - label: check typescript api
    if: *not-scheduled
    depends_on:
      - build-ligo
      - build-haskell
    commands:
      - nix run -f ci.nix packages.segmented-cfmm.exes.segmented-cfmm pkgs.diffutils -c ./scripts/ci/validate-typescript-api.sh


  - label: typescript-build
    if: *not-scheduled
    depends_on:
      - build-ligo
      - build-haskell
    commands:
    - nix-build ci.nix -A build-typescript --arg release false

  - label: weeder
    if: *not-scheduled
    depends_on: build-haskell
    commands:
    - nix-build ci.nix -A weeder-script
    - ./result

  - label: haddock
    if: *not-scheduled
    depends_on: build-haskell
    commands:
    - nix-build ci.nix -A haddock --no-out-link

notify:
  - email: "tezos-alerts@serokell.io"
    if: build.state == "failed" && build.source == "schedule"
