# SPDX-FileCopyrightText: 2021 Arthur Breitman
# SPDX-License-Identifier: LicenseRef-MIT-Arthur-Breitman

steps:
  - label: reuse lint
    commands:
    - nix run -f ci.nix pkgs.reuse -c
        reuse lint

  - label: check trailing whitespace
    commands:
    - .buildkite/check-trailing-whitespace.sh

  - label: xrefcheck
    commands:
    - nix run -f ci.nix xrefcheck -c xrefcheck
    retry:
      automatic:
        limit: 1

  - label: build-ligo
    key: build-ligo
    commands:
      - nix-build ci.nix -A build-ligo -o ./ligo-out/
    artifact_paths:
      - ligo-out/segmented_cfmm.tz
